spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskify_db
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

jwt:
  secret: your_jwt_secret_key
  expiration: 86400000 # 1 day in milliseconds
